---
- name: EDA | AlertManager | Listen for events from AlertManager
  hosts: localhost

  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: EDA-AlertManager-Run playbook to handle alerts
      condition: event.payload.status == "firing"
      action:
        run_job_template:
          name: "Resize PVC"
          organization: Default
          job_args:
            extra_vars:
              alerts: "{{ event.payload.alerts[0] }}"
              alert_description: "{{ event.payload.alerts[0].annotations.description }}"
              alert_summary: "{{ event.payload.alerts[0].annotations.summary }}"
              alertStatus: "{{ event.payload.status }}"
