---
- name: Watch for Secret Changes in OpenShift
  hosts: localhost
  sources:
    - name: Watch OpenShift Secrets
      ansible.eda.kubernetes:
        kind: Secret
        namespace: mywebapp
        kubeconfig: /etc/ansible/kubeconfig.yaml
        label_selector: "app=mywebapp"

  rules:
    - name: Restart Deployment on Secret Update
      condition: event.type == "MODIFIED"
      action:
        run_playbook:
          name: restart_deployment.yml
          extra_vars:
            namespace: mywebapp
            deployment: mywebapp
