---
- name: Watch for Secret Changes in OpenShift
  hosts: localhost
  sources:
    - name: Watch OpenShift Secrets
      kubernetes.core.k8s_event:
        kind: Secret
        namespace: mywebapp
        kubeconfig: /app/kubeconfig.yaml
        label_selector: "app=mywebapp"

  rules:
    - name: Restart Deployment on Secret Update
      condition: event.type == "MODIFIED"
      action:
        run_job_template:
          name: /app/restart_deployment.yml
          extra_vars:
            namespace: mywebapp
            deployment: mywebapp
