---
- name: Watch for Secret Changes in OpenShift
  hosts: localhost
  sources:
    - name: Watch OpenShift Secrets
      sabre1041.eda.k8s:
        kind: Secret
        namespace: mywebapp
        kubeconfig: /app/kubeconfig.yaml  # Dosyanın path’ini doğrula
        label_selector: "app=mywebapp"

  rules:
    - name: Restart Deployment on Secret Update
      condition: event.payload.object.metadata.name is defined
      action:
        run_job_template:
          name: restart_deployment.yml
          inventory: /app/inventory.ini  # INVENTORY TANIMLANDI!
          extra_vars:
            namespace: mywebapp
            deployment: mywebapp

