---
- name: Watch for Secret Changes in OpenShift
  hosts: localhost
  sources:
    - name: Watch OpenShift Secrets
      sabre1041.eda.k8s:
        kind: Secret
        namespace: mywebapp
        kubeconfig: /app/kubeconfig.yaml
        label_selector: "app=mywebapp"

  rules:
    - name: Restart Deployment on Secret Update
      condition: event.type == "MODIFIED" and event.resource.metadata.name == "mywebapp-db-password"
      action:
        run_job_template:
          name: /app/restart_deployment.yml
          extra_vars:
            namespace: mywebapp
            deployment: mywebapp
